// <auto-generated />
namespace Budgetor.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reseeddatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reseeddatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201605142319346_reseed-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
